import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#ffffffff', // Mismo fondo que NotificationsScreen
  },
  scrollContent: {
    paddingHorizontal: 20, // Margen lateral consistente
    paddingBottom: 40,
  },
  headerWithNotification: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    paddingBottom: 5,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  mainTitle: {
    fontWeight: '700',
    fontSize: 24,
    color: '#1f2937',
  },
  subtitleFixed: {
    fontSize: 16,
    color: '#6b7280',
    lineHeight: 22,
    marginTop: 19,
    marginBottom: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffffff',
    padding: 20,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#7f8c8d',
  },
  errorTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2c3e50',
    marginTop: 15,
  },
  errorSubtitle: {
    fontSize: 14,
    color: '#7f8c8d',
    textAlign: 'center',
    marginTop: 10,
    paddingHorizontal: 30,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    marginVertical: 10,
    alignContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  iconoGrandeContainer: {
    alignItems: 'center', 
    marginBottom: 10,
  },
  emojiGrande: {
    fontSize: 60,
    textAlign: 'center',
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2c3e50',
    marginBottom: 15,
  },
  percentText: {
    fontSize: 42,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 10,
  },
  progressContainer: {
    height: 12,
    backgroundColor: '#ecf0f1',
    borderRadius: 6,
    overflow: 'hidden',
    marginVertical: 15,
  },
  progressBar: {
    height: '100%',
    borderRadius: 6,
  },
  subText: {
    fontSize: 13,
    color: '#7f8c8d',
    textAlign: 'center',
    marginTop: 5,
  },
  motivationalBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginVertical: 10,
    borderLeftWidth: 4,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  motivationalText: {
    fontSize: 15,
    color: '#2c3e50',
    marginLeft: 10,
    flex: 1,
    lineHeight: 22,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  statsLabel: {
    flex: 1,
    fontSize: 15,
    color: '#2c3e50',
    marginLeft: 10,
  },
  statsValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#3498db',
  },
  emocionItem: {
    backgroundColor: '#f8f9fa',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#00723f',
  },
  emocionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  emocionFecha: {
    fontSize: 12,
    color: '#7f8c8d',
    marginLeft: 8,
    fontWeight: '600',
  },
  emocionPregunta: {
    fontSize: 13,
    color: '#34495e',
    marginBottom: 3,
    fontStyle: 'italic',
  },
  emocionRespuesta: {
    fontSize: 15,
    color: '#2c3e50',
    fontWeight: '600',
  },
  infoBox: {
    backgroundColor: '#e3f2fd',
    borderRadius: 12,
    padding: 15,
    marginVertical: 10,
    marginBottom: 30,
  },
  infoText: {
    fontSize: 13,
    color: '#1565c0',
    lineHeight: 20,
  },
});